2024-KDT-JNA/Pentoryall

build.gradle
settings.gradle
src/main/java/com/pentoryall/PentoryallApplication.java
src/test/java/com/pentoryall/PentoryallApplicationTests.java

🚀 resolved #5
- 프로젝트 경로(네이밍)을 올바르게 변경하였습니다.

#5 프로젝트 네이밍 변경

---

src/main/java/com/pentoryall/admin/Controller/commentReportController.java
src/main/java/com/pentoryall/admin/Controller/genreManageController.java
src/main/java/com/pentoryall/admin/Controller/modifyPostController.java
src/main/java/com/pentoryall/admin/Controller/payManageController.java
src/main/java/com/pentoryall/admin/Controller/postReportController.java
src/main/java/com/pentoryall/admin/Controller/userManageController.java
src/main/java/com/pentoryall/admin/DTO/genreManageDTO.java
src/main/java/com/pentoryall/admin/DTO/noticeManageDTO.java
src/main/java/com/pentoryall/admin/DTO/reportManage.java
src/main/java/com/pentoryall/admin/DTO/userManageDTO.java
src/main/java/com/pentoryall/admin/DTO/userSettlementDTO.java
src/main/java/com/pentoryall/admin/Service/commentReportService.java
src/main/java/com/pentoryall/admin/Service/genreManageService.java
src/main/java/com/pentoryall/admin/Service/modifyPostService.java
src/main/java/com/pentoryall/admin/Service/payManageService.java
src/main/java/com/pentoryall/admin/Service/postReportService.java
src/main/java/com/pentoryall/admin/Service/userManageService.java

#15 관리자 패키지 설계

---

src/main/java/com/pentoryall/point/controller/OrderController.java
src/main/java/com/pentoryall/point/controller/TransactionController.java
src/main/java/com/pentoryall/point/dto/ImpOrderDTO.java
src/main/java/com/pentoryall/point/dto/OrderDTO.java
src/main/java/com/pentoryall/point/dto/TransactionDTO.java
src/main/java/com/pentoryall/point/mapper/OrderMapper.java
src/main/java/com/pentoryall/point/mapper/TransactionMapper.java
src/main/java/com/pentoryall/point/service/OrderService.java
src/main/java/com/pentoryall/point/service/TransactionService.java

포인트 충전 및 거래 패키지 구조
🚀 closed #20, #21
- 포인트 충전 및 거래 패키지 작성 (controller, service, mapper, dto)

#20, #21 포인트 충전 및 거래 패키지 구조

---

src/main/java/com/pentoryall/user/controller/UserController.java
src/main/java/com/pentoryall/user/dto/UserDTO.java
src/main/java/com/pentoryall/user/mapper/UserMapper.java
src/main/java/com/pentoryall/user/service/UserService.java

#16 회원패키지 구조 설계

---

src/main/java/com/pentoryall/user/controller/LikeController.java
src/main/java/com/pentoryall/user/controller/UserController.java
src/main/java/com/pentoryall/user/dto/LikeDTO.java
src/main/java/com/pentoryall/user/dto/UserDTO.java
src/main/java/com/pentoryall/user/mapper/LikeMapper.java
src/main/java/com/pentoryall/user/mapper/UserMapper.java
src/main/java/com/pentoryall/user/service/LikeService.java
src/main/java/com/pentoryall/user/service/UserService.java

#17 좋아요패키지 구조 설계

---

src/main/java/com/pentoryall/membership/controller/MembershipController.java
src/main/java/com/pentoryall/membership/dto/MembershipDTO.java
src/main/java/com/pentoryall/membership/dto/MembershipJoinDTO.java
src/main/java/com/pentoryall/membership/service/MembershipService.java
src/main/java/com/pentoryall/subscribe/controller/SubscribeController.java
src/main/java/com/pentoryall/subscribe/dto/SubscribeDTO.java
src/main/java/com/pentoryall/subscribe/service/SubscriberService.java

 #12, #18 멤버십/ 구독 기초설계 

---

src/main/java/com/pentoryall/common/controller/MainController.java
src/main/resources/static/css/admin.css
src/main/resources/static/css/common.css
src/main/resources/static/css/main.css
src/main/resources/static/css/post.css
src/main/resources/static/css/story.css
src/main/resources/static/css/sub.css
src/main/resources/static/css/user.css
src/main/resources/static/js/common.js
src/main/resources/static/js/main.js
src/main/resources/templates/fragments/footer.html
src/main/resources/templates/fragments/head.html
src/main/resources/templates/fragments/header.html
src/main/resources/templates/fragments/links.html
src/main/resources/templates/fragments/scripts.html
src/main/resources/templates/fragments/story/header.html
src/main/resources/templates/layout/default.html
src/main/resources/templates/layout/story.html
src/main/resources/templates/views/_sample.html
src/main/resources/templates/views/index.html
src/main/resources/templates/views/story/_sample.html
src/main/resources/templates/views/story/home.html

🚀 closed #4
- #3
- #4
1. **경로 설정을 위한 컨트롤러 추가됨** (임시로 사용할 용도)
-  `/common/controller/MainController.java` 
- 메인 화면으로 설정된 경로:  `/`, `/main`, `/index`
- 스토리 홈 화면으로 설정된 경로: `/story`
2.  css, js 추가 및 변경됨
3. **thymeleaf layout 적용**
- 샘플 파일 복사 후 주석 내용 참고하여 페이지 작성하세요.
- 공통 레이아웃 (`/templates/layout/default.html`) : 대부분의 페이지에서 사용될 레이아웃
- (적용 예시) 메인 화면 : `/templates/views/index.html`
- (샘플 파일) `/templates/views/_sample.html` 
- 마이 스토리 레이아웃  (`/templates/layout/story.html`)
- (적용 예시)  스토리 홈 화면 : (`/templates/views/story/home.html`)
- (샘플 파일) `/templates/views/story/_sample.html` 참고

#3, #4 Thymeleaf Layout 적용

---

src/main/java/com/pentoryall/email/service/EmailSendService.java
src/main/resources/static/_views/main.html
src/main/resources/templates/fragments/header.html
src/main/resources/templates/fragments/story/header.html
src/main/resources/templates/views/membership/failCreate.html
src/main/resources/templates/views/membership/successCreate.html

#59
- 프로젝트 클론 후 재설정 완료
- 멤버십 DTO 설정 / html 아직 수정중 / service , controller 수정중

#59 멤버십 기능 관련 파일 추가

---

src/main/java/com/pentoryall/common/exception/GlobalExceptionHandler.java
src/main/java/com/pentoryall/config/SecurityConfig.java
src/main/java/com/pentoryall/user/controller/UserController.java
src/main/resources/static/js/common.js
src/main/resources/static/js/event.js
src/main/resources/templates/views/user/regist.html

🚀#46, #69 
- `common.js` 오류를 수정
- 이전 PR 머지 후 발생하는 오류를 수정

#46, #69 Merge 오류 수정

---

src/main/java/com/pentoryall/post/mapper/PostMapper.java
src/main/java/com/pentoryall/post/service/PostService.java
src/main/java/com/pentoryall/series/controller/SeriesController.java
src/main/java/com/pentoryall/series/mapper/SeriesMapper.java
src/main/java/com/pentoryall/series/service/SeriesService.java
src/main/java/com/pentoryall/user/mapper/UserMapper.java
src/main/java/com/pentoryall/user/service/UserService.java
src/main/resources/mappers/PostMapper.xml
src/main/resources/mappers/SeriesMapper.xml
src/main/resources/mappers/UserMapper.xml
src/main/resources/static/css/main.css
src/main/resources/templates/fragments/header.html
src/main/resources/templates/views/series/page.html
src/main/resources/templates/views/series/select.html

#98 제목,작가,제목+작가 검색에 따른 결과 출력

---

src/main/java/com/pentoryall/comment/dto/CommentDetailDTO.java
src/main/java/com/pentoryall/comment/mapper/CommentMapper.java
src/main/java/com/pentoryall/comment/service/CommentService.java
src/main/java/com/pentoryall/post/controller/PostController.java
src/main/resources/mappers/CommentMapper.xml
src/main/resources/templates/views/post/list.html
src/main/resources/templates/views/post/writer.html

#111 댓글 수정 기능 추가

---

src/main/java/com/pentoryall/story/controller/StoryController.java
src/main/resources/templates/fragments/story/header.html
src/main/resources/templates/views/story/home.html
src/main/resources/templates/views/story/posts.html
src/main/resources/templates/views/story/series.html

🚀 closed #158
- Story 경로 패턴을 `/story/{userId}` 형태로 변경
- 관련 페이지 링크도 수정
- 스토리 페이지의 post, series 가 없을 때 표시할 html 추가

#158 스토리 경로 변경

---

src/main/java/com/pentoryall/membership/mapper/MembershipMapper.java
src/main/java/com/pentoryall/membership/service/MembershipService.java
src/main/java/com/pentoryall/point/controller/PointTransactionApiController.java
src/main/java/com/pentoryall/point/controller/PointTransactionController.java
src/main/java/com/pentoryall/point/dto/TransactionDTO.java
src/main/java/com/pentoryall/point/mapper/TransactionMapper.java
src/main/java/com/pentoryall/point/service/TransactionService.java
src/main/java/com/pentoryall/post/controller/PostApiController.java
src/main/java/com/pentoryall/post/controller/PostController.java
src/main/java/com/pentoryall/post/dto/ValidatePostDTO.java
src/main/java/com/pentoryall/post/mapper/PostMapper.java
src/main/java/com/pentoryall/post/service/PostService.java
src/main/java/com/pentoryall/series/controller/SeriesController.java
src/main/java/com/pentoryall/user/mapper/UserMapper.java
src/main/resources/mappers/MembershipMapper.xml
src/main/resources/mappers/PostMapper.xml
src/main/resources/mappers/TransactionMapper.xml
src/main/resources/static/js/post.js
src/main/resources/templates/fragments/header.html
src/main/resources/templates/views/membership/register.html
src/main/resources/templates/views/series/page.html

🚀 closed #82
-  포스트 구매  
- 구매자의 보유 포인트 소모
- 판매자의 보유 수익 증가
- 유료 포스트 구매 로직
- 유료 포스트 조회 시 검증 로직
- 그 외 url 변경
- 유료 포스트 조회 시 검증 로직은 `post.js`에 있으며, 모든 포스트 조회 시 onclick 이벤트로 `onClickValidatePost( 포스트코드 )` 를 걸어주어야 작동합니다.

#82 유료 포스트 거래

---

src/main/java/com/pentoryall/settlement/controller/SettlementController.java
src/main/resources/static/css/point.css
src/main/resources/templates/fragments/post/purchasePopup.html
src/main/resources/templates/views/membership/register.html
src/main/resources/templates/views/point/order.html
src/main/resources/templates/views/point/orderList.html
src/main/resources/templates/views/point/orderResult.html
src/main/resources/templates/views/settlement/revenueList.html
src/main/resources/templates/views/settlement/settlement.html
src/main/resources/templates/views/settlement/settlementList.html
src/main/resources/templates/views/settlement/settlementResult.html

🚀 #83
- 페이지 연결
- 정산 신청 및 결과
- 정산 신청 목록
- 수익 적립 내역

#83 수익 및 정산 관련 페이지 추가

---

src/main/java/com/pentoryall/point/controller/PointTransactionApiController.java
src/main/java/com/pentoryall/story/controller/StoryController.java
src/main/resources/templates/fragments/story/header.html

스토리 홈 오류 수정 및 탭 처리
- 스토리 홈에서 발생하던 포스트/시리즈 범위 관련 오류 수정함 
- StoryController에서 `TAB_MENU` 값을 보내주어서 탭 환성화 여부를 처리함

스토리 홈 오류 수정 및 탭 처리

---

src/main/java/com/pentoryall/common/page/Pagination.java
src/main/java/com/pentoryall/settlement/controller/SettlementController.java
src/main/java/com/pentoryall/settlement/dto/UserRevenueDTO.java
src/main/java/com/pentoryall/settlement/mapper/SettlementMapper.java
src/main/java/com/pentoryall/settlement/service/SettlementService.java
src/main/resources/mappers/SettlementMapper.xml
src/main/resources/templates/views/settlement/revenueList.html
src/main/resources/templates/views/settlement/settlementList.html

🚀 #83, closed #172
- 기능 구현
- 수익 적립 내역 (`/settings/revnue/list`) 
-  정산 요청 내역  (`/settings/settlement/list`)
- 단, 검색 옵션 등의 기능은 아직 미구현

#83, 172 수익 적립 내역, 정산 요청 내역

---

src/main/java/com/pentoryall/point/service/TransactionService.java
src/main/java/com/pentoryall/portone/controller/PortOneApiController.java
src/main/java/com/pentoryall/portone/service/PortOneService.java
src/main/java/com/pentoryall/settlement/controller/SettlementController.java
src/main/java/com/pentoryall/settlement/dto/SettlementDTO.java
src/main/java/com/pentoryall/settlement/mapper/SettlementMapper.java
src/main/java/com/pentoryall/settlement/service/SettlementService.java
src/main/resources/mappers/SettlementMapper.xml
src/main/resources/static/css/common.css
src/main/resources/static/css/point.css
src/main/resources/static/css/sub.css
src/main/resources/static/js/settlement.js
src/main/resources/templates/views/settlement/settlement.html
src/main/resources/templates/views/user/settlement/add.html

🚀 closed #83
- 정산 요청 기능 완료 (`/settings/settlement`)

#83 정산 요청 기능

---

src/main/resources/static/css/common.css
src/main/resources/templates/fragments/header.html
src/main/resources/templates/views/settlement/settlement.html
src/main/resources/templates/views/story/home.html

🚀 closed #188
-  관리자 로그인 시 [관리자 페이지] 버튼의 링크 변경 
- 정산 요청 페이지의 null 처리

#188 관리자 페이지 링크 및 정산 요청 페이지의 null 처리

---

src/main/java/com/pentoryall/admin/controller/CommentReportController.java
src/main/java/com/pentoryall/admin/controller/ModifyPostController.java
src/main/java/com/pentoryall/admin/controller/PostReportController.java
src/main/java/com/pentoryall/admin/controller/SettlementManageController.java
src/main/resources/mappers/SettlementManageMapper.xml
src/main/resources/static/css/admin.css
src/main/resources/templates/views/admin/adminCommentReport.html
src/main/resources/templates/views/admin/adminPostModify.html
src/main/resources/templates/views/admin/adminPostReport.html
src/main/resources/templates/views/admin/adminSettlement.html
src/main/resources/templates/views/admin/adminUser.html

🚀 closed #191
- html 태그 수정
- css 일부 수정
- controller, mapper 일부 수정

#191 관리자 페이지 html, css, js 일부 수정

---

src/main/java/com/pentoryall/point/controller/PointTransactionController.java
src/main/java/com/pentoryall/point/dto/UserPurchaseDTO.java
src/main/java/com/pentoryall/point/mapper/OrderMapper.java
src/main/java/com/pentoryall/point/mapper/TransactionMapper.java
src/main/java/com/pentoryall/point/service/TransactionService.java
src/main/java/com/pentoryall/settlement/mapper/SettlementMapper.java
src/main/java/com/pentoryall/settlement/service/SettlementService.java
src/main/resources/mappers/SettlementMapper.xml
src/main/resources/mappers/TransactionMapper.xml
src/main/resources/static/css/common.css
src/main/resources/templates/views/point/purchaseList.html

🚀 closed #193
- 포인트 충전 내역 조회 관련 로직을 Refactoring  
- `settlementMapper` -> `transactionMapper`
- 포인트 사용 내역 조회 구현
- 기타 css 수정

#193 포인트 충전 및 사용 내역
